package com.ll.simpleDb;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.PropertyAccessor;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class SimpleDb {
    private final Connection connection;
    private boolean devMode;
    private ObjectMapper om = new ObjectMapper() {{
        registerModule(new JavaTimeModule());
        setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
    }};

    public SimpleDb(String host, String username, String password, String dbName) {
        int port = 3306;

        String url = "jdbc:mysql://" + host + ":" + port + "/" + dbName
                + "?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull";

        connection = createConnection(url, username, password);
    }

    private Connection createConnection(String url, String username, String password) {
        try {
            return DriverManager.getConnection(url, username, password);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void setDevMode(boolean mode) {
        this.devMode = mode;
    }

    public Sql genSql() {
        return new Sql(this);
    }

    private void printRawSql(String sql, Object[] args) {
        if (!devMode) return;

        System.out.println("== rawSql ==");
        System.out.println(genRawSql(sql, args));
        System.out.println();
    }

    private String genRawSql(String sql, Object[] args) {
        for (Object arg : args) {
            if (arg instanceof Boolean) {
                arg = (boolean) arg ? 1 : 0;
            }

            Pattern pattern = Pattern.compile("(?<![\"'])\\?(?![\"'])");
            Matcher matcher = pattern.matcher(sql);

            // Matcher의 인덱스를 끝에서 시작하도록 설정
            int lastIndex = sql.length();

            while (lastIndex > 0) {
                matcher.region(0, lastIndex);
                if (matcher.find()) {
                    lastIndex = matcher.start();

                    int start = lastIndex;
                    int end = matcher.end();
                    sql = sql.substring(0, start) + "'" + arg + "'" + sql.substring(end);
                } else {
                    break;
                }
            }
        }

        return sql;
    }

    private void setPreparedStatementParameters(PreparedStatement preparedStatement, Object[] args) throws SQLException {
        for (int i = 0; i < args.length; i++) {
            preparedStatement.setObject(i + 1, args[i]);
        }
    }

    private long executeSql(String sql, Object[] args, int autoGeneratedKeys) {
        printRawSql(sql, args);

        try (PreparedStatement preparedStatement = connection.prepareStatement(sql, autoGeneratedKeys)) {
            setPreparedStatementParameters(preparedStatement, args);
            if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) {
                preparedStatement.executeUpdate();
                return getGeneratedKey(preparedStatement);
            } else {
                return preparedStatement.executeUpdate();
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private long getGeneratedKey(PreparedStatement preparedStatement) throws SQLException {
        ResultSet generatedKeys = preparedStatement.getGeneratedKeys();

        if (generatedKeys.next()) {
            return generatedKeys.getLong(1);
        } else {
            throw new RuntimeException("No generated key was returned after insert");
        }
    }

    private <T> List<T> selectSql(String sql, Object[] args, Class<T> cls) {
        List<T> result;

        printRawSql(sql, args);

        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            setPreparedStatementParameters(preparedStatement, args);
            ResultSet resultSet = preparedStatement.executeQuery();

            result = extractResultRows(resultSet, cls);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        return result;
    }

    private <T> List<T> selectSql(String sql, Object[] args) {
        return selectSql(sql, args, (Class<T>) Map.class);
    }

    private <T> List<T> extractResultRows(ResultSet resultSet, Class<T> cls) throws SQLException {
        List<T> rows = new ArrayList<>();
        ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
        int columnCount = resultSetMetaData.getColumnCount();

        while (resultSet.next()) {
            Map<String, Object> row = new HashMap<>();

            for (int i = 1; i <= columnCount; i++) {
                String columnName = resultSetMetaData.getColumnLabel(i);
                Object columnValue = resultSet.getObject(i);
                row.put(columnName, columnValue);
            }

            if (cls.getSimpleName().equals("Map")) {
                rows.add((T) row);
            } else {
                rows.add(om.convertValue(row, cls));
            }
        }

        return rows;
    }

    public void run(String sql, Object... args) {
        executeSql(sql, args, Statement.NO_GENERATED_KEYS);
    }

    public long runInsert(String sql, Object... args) {
        return executeSql(sql, args, Statement.RETURN_GENERATED_KEYS);
    }

    public long runUpdate(String sql, Object[] args) {
        return executeSql(sql, args, Statement.NO_GENERATED_KEYS);
    }

    public <T> List<T> runSelectRows(String sql, Object[] args, Class<T> cls) {
        return selectSql(sql, args, cls);
    }

    public Map<String, Object> runSelectRow(String sql, Object[] args) {
        List<Map<String, Object>> rows = selectSql(sql, args);

        if (rows.isEmpty()) {
            return null;
        }

        return rows.get(0);
    }

    private Object runSelectObject(String sql, Object[] args) {
        Map<String, Object> row = runSelectRow(sql, args);

        if (row == null) {
            return null;
        }

        return row.entrySet().iterator().next().getValue();
    }

    public LocalDateTime runSelectDatetime(String sql, Object[] args) {
        return (LocalDateTime) runSelectObject(sql, args);
    }

    public Long runSelectLong(String sql, Object[] args) {
        return (Long) runSelectObject(sql, args);
    }

    public String runSelectString(String sql, Object[] args) {
        return (String) runSelectObject(sql, args);
    }

    public Boolean runSelectBoolean(String sql, Object[] args) {
        Object bool = runSelectObject(sql, args);

        if (bool instanceof Integer) return (Integer) bool == 1;
        return (Boolean) bool;
    }

    public List<Long> runSelectLongs(String sql, Object[] args) {
        List<Map<String, Object>> rows = selectSql(sql, args);
        List<Long> result = new ArrayList<>();

        for (Map<String, Object> row : rows) {
            result.add((Long) row.entrySet().iterator().next().getValue());
        }

        return result;
    }

    public List<String> runSelectStrings(String sql, Object[] args) {
        List<Map<String, Object>> rows = selectSql(sql, args);
        List<String> result = new ArrayList<>();

        for (Map<String, Object> row : rows) {
            result.add((String) row.entrySet().iterator().next().getValue());
        }

        return result;
    }

    public List<LocalDateTime> runSelectDatetimes(String sql, Object[] args) {
        List<Map<String, Object>> rows = selectSql(sql, args);
        List<LocalDateTime> result = new ArrayList<>();

        for (Map<String, Object> row : rows) {
            result.add((LocalDateTime) row.entrySet().iterator().next().getValue());
        }

        return result;
    }

    public List<Boolean> runSelectBooleans(String sql, Object[] args) {
        List<Map<String, Object>> rows = selectSql(sql, args);
        List<Boolean> result = new ArrayList<>();

        for (Map<String, Object> row : rows) {
            Object bool = row.entrySet().iterator().next().getValue();

            if (bool instanceof Integer) bool = (Integer) bool == 1;
            result.add((Boolean) bool);
        }

        return result;
    }
}